CREATE TYPE event_type AS ENUM ('diaper_changes', 'feedings', 'appointments', 'stretches');

CREATE TABLE events (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    title event_type NOT NULL,
    content TEXT NOT NULL,
    date_added TIMESTAMPTZ DEFAULT now() NOT NULL,
    user_id INTEGER REFERENCES users(id) ON DELETE CASCADE NOT NULL
);